import random

x = 0
y = -1
z = 0
# Kelime listesi (güncel haliyle)
words = {
    "except": "hariç",
    "continental" : "karasal",
    "occupation": "meslek",
    "through": "içinden geçme",
    "towards": "-e doğru",
    "composer": "besteci",
    "obviously": "apaçık",
    "polluted": "kirli",
    "impatient": "sabırsız",
    "frustrated": "hayalkırıklığına uğramak",
    "annoying": "sinir bozucu",
    "nutritionist": "diyetisyen",
    "low-fat": "az yağlı",
    "Towels": "Havlular",
    "borrow": "ödünç almak",
    "lay off (non fomral)" : "kovulmak",
    "enthusiastic": "hevesli",
    "wake" : "uyanmak",
    "forecast" : "yayın",
    "Reach" : "ulaşmak",
    "discuss" : "tartışmak",
    "Contex" : "bağlam",
    "Mourn" : "yas tutmak",
    "Expressing" : "ifade etmek",
    "Deadline" : "zaman sınırı",
    "So (cümle başında)" : "pekala",
    "Be able" : "yapabilmek",
    "be able to" : "ebilmek",
    "Schedule" : "takvim",#plan program
    "let that situation affect" : "durumun etkilemesine izin vermek",
    "consider" : "hesaba katmak",
    "including" : "dahil olmak üzere",
    "bottom" : "dip",
    "reliable" : "güvenilir",
    "bootleg" : "çakma",
    "indeed" : "gerçekten de",
    "swers" : "kanalizasyon",
    "desperately" : "umutsuzca",
    "drastic" : "şiddetli",
    "measures" : "tedbir",
    "relying" : "güvenerek",
    "swift" : "seri",
    "tight" : "sıkı",
    "squadron" : "filo",
    "regiment (askeri birlik)" : "alay",
    "cavalry" : "süvari",
    "urgent" : "ivedi",
    "division" : "Bölük",
    "Means" : "vasıta", #radyo,telsiz
    "instead" : "yerine",
    "drew (çubuk)" : "çekmek",
    "regret" : "pişmanlık",
    "whatsoever" : "ne olursa olsun",
    "promotion" : "terfi",
    "eager" : "istekli",
    "loaf" : "somun ekmek",
    "spanner" : "somun anahtar",
    "glad" : "memnun",
    "mind (V)" : "sakınca görmek",
    "avoid" : "kaçınmak",
    "admit" : "itiraf etmek",
    "refuse" : "reddetmek",
    "manage" : "işletmek",
    "afford" : "parası yetmek",
    "regret" : "pişmanlık",
    "I'm looking forward" : "sabırsızlanmak",
    "look forward to" : "sabırsızlıkla beklemek",
    "Means" : "araç", #gereç, alet
    "clarification" : "açıklama",
    "wrop up" : "sonlandırmak",
    "Wrop" : "dürmek",
    "Go over" : "üzerinden geçmek",
    "Give in" : "pes etmek",
    "Break out" : "kaçmak",
    "Break down" : "bozulmak",
    "skirt" : "etek",
    "tights" : "tayt",
    "although" : "rağmen",
    "colleague" : "meslektaş",
    "I doubt it. " : "şüpheliyim",
    "obtain" : "elde etmek",
    "persuade" : "ikna edici",
    "rub" : "ovmak",
    "shout" : "bağırmak",
    "arrogant" : "kibirli",
    "confidence" : "güven",
    "indecisive" : "kararsız",
    "adopt" : "sahiplenmek",
    "unrelated" : "alakasız",
    "related" : "alakalı",
    "poetry" : "şiir",
    "proud" : "gururlu",
    "curious" : "meraklı",
    "annoy" : "rahatsız etmek",
    "pale" : "solgun",
    "straight away" : "derhal",
    "affectionate" : "sevecen",
    "ambitious" :"hırslı",
    "anxious" : "endişeli",
    "bossy" : "üstünlük taslayan",
    "charming" : "çekici",
    "competitive" : "rekabetçi",
    "honest" : "dürüst",
    "imaginative" : "hayalperest",
    "independent" : "bağımsız",
    "insecure" : "özgüvensiz",
    "mature" : "olgun",
    "moody" : "huysuz",
    "patient" : "sabırlı",
    "rebellious" : "asi",
    "self-confident" : "özgüvenli",
    "selfish" : "bencil",
    "sensible" : "mantıklı",
    "sensitive" : "hassas",
    "sociable" : "sosyal",
    "spoilt" : "nazlı",
    "stubborn" : "inatçı",
    "cheque" : "çek",
    "charge" : "suçlama",
    "owe" : "borçlu olmak",
    "loan" : "kredi",
    "budget" : "bütçe",
    "inherited" : "miras",
    "bring along" : "beraberinde getirmek",
    "after all" : "buna karşın",
    "at least" : "en az",
    "topic" : "konu",
    "reliability" : "güvenilirlik",
    "excessive" : "aşırı",
    "bill" : "fatura",
    "borrow" : "ödünç almak",
    "budget" : "bütçe",
    "charge" : "hizmet karşılığı para",
    "cost" : "tutar",
    "earn" : "kazanmak",
    "inherit" : "miras",
    "insurance" : "sigorta",
    "invest" : "yatırım yapmak",
    "lend" : "ödünç vermek",
    "live off" : "ayrı yaşamak",
    "live on" : "hayatta kalmak",
    "loan" : "kredi",
    "mortgage" : "ipotek",
    "note" : "banknot",
    "owe" : "borçlu olmak",
    "pay" : "ödemek",
    "pay back" : "geri ödeme",
    "raise money" : "para toplamak",
    "salary" : "maaş",
    "save" : "biriktirmek",
    "spend" : "harcamak",
    "take out" : "bankamatikten para almak",
    "tax" : "vergi",
    "waste" : "israf",
    "worth" : "değer",
    "beauty treatment" : "estetik",
    "cash machine" : "ATM",
    "cleaning product" : "temizlik ürünü",
    "cycling trip" : "bisiklet gezisi",
    "electricity bill" : "elektrik faturası",
    "olive oil" : "zeytin yağı",
    "tap water" : "musluk suyu",
    "amazed" : "şaşkın",
    "boiling" : "kaynamak",
    "delighted" : "memnun olmak",
    "enormous" : "devasa",
    "exhausted" : "yorulmuş",
    "fascinating" : "büyüleyici",
    "filthy" : "pis",
    "freezing" : "donmak",
    "furious" : "öfkeli",
    "hilarious" : "gülünç",
    "huge" : "büyük",
    "positive" : "pozitif",
    "starving" : "açlıktan ölmek",
    "terrified" : "dehşete düşmüş",
    "tiny" : "ufak",
    "scam" : "tuzak",
    "currency" : "para birimi",
    "coin" : "madeni para",
    "achieve" : "başarmak",
    "advice" : "tavsiye",
    "discover" : "keşfetmek",
    "survive" : "hayatta kalmak",
    "investment" : "yatırım",
    "codition" : "durum",
    "organization" : "organizasyon",
    "possession" : "mülk",
    "support" : "destek",
    "event" : "olay",
    "raise money" : "para toplamak",
    "challange" : "meydan okuma",
    "journey" : "seyehat",
    "destination" : "varış noktası",
    "complete" : "tamamlamak",
    "emotional" : "duygusal",
    "scenery" : "manzara",
    "incredible" : "inanılmaz",
    "car crash" : "araba kazası",
    "coach" : "otobüs",
    "cycle lane" : "bisiklet yolu",
    "end up" : "sonlanmak",
    "ferry" : "feribot",
    "lorry" : "kamyon",
    "motorbike" : "motorsiklet",
    "motorway" : "otoyol",
    "parking fine" : "park cezası",
    "pedestrian zone" : "yaya bölgesi",
    "petrol station" : "benzinci",
    "roadworks" : "yol çalışmaları",
    "run out" : "tükenmek",
    "rush our" : "iş çıkış saati",
    "scooter" : "skutır",
    "seat belt" : "emniyet kemeri",
    "set off" : "yola koyulmak",
    "speed camera" : "radar",
    "taxi rank" : "taksi durağı",
    "tram" : "tramvay",
    "underground" : "metro",
    "van" : "kamyonet",
    "watch / look out !" : "dikkat et",
    "belong to" : "ait olmak",
    "fed up with" : "bıkmış",
    "fond of" : "düşkün",
    "keen on" : "meraklı",
    "kind to" : "nazik",
    "sensible" : "mantıklı",
    "tend" : "yatkın olma",
    "turn out" : "boşaltmak",
    "adjust" : "ayarlamak",
    "dialling" : "çevirme",
    "engaged" : "nişanlı",
    "go off" : "gitmek",
    "appropriate" : "uygun",
    "busking" : "sokak müzisyeni",
    "inappropriate" : "uygunsuz",
    "circuit" : "devre",
    "coach" : "eğitmen",
    "course" : "kurs",
    "muddy" : "çamurlu",
    "slope" : "eğim",
    "fancy" : "süslü",
    "fiance" : "nişanlı",
    "superstition" : "batıl inanç",
    "trophy" : "ödül",
    "increase" : "arttırmak",
    "criticize" : "eleştirmek",
    "umpire" : "hakem",
    "bounce" : "sıçrama",
    "audience" : "seyirci",
    "dub" : "dublaj",
    "plot" : "entrika",
    "rom-coms" : "romantik komediler",
    "sequel" : "devam filmi",
    "thriller" : "gerilim",
    "nod" : "kafa sallamak",
    "whistle" : "düdük",
    "adore" : "tapmak",
    "dedicated" : "adanmış",
    "up to date" : "güncel",
    "matter" : "madde",
    "gesture" : "jest",
    "impression" : "izlenim",
    "dozen" : "düzinelerce",
    "deflate" : "söndürmek",
    "inflatable" : "şişirilebilir",
    "literary" : "edebi",
    "accomplish" : "başarmak",
    "incompetent" : "yetersiz",
    "sligghtly" : "biraz",
    "expel" : "kovmak",
    "attic" : "çatı katı",
    "chimney" : "baca",
    "ceiling" : "tavan",
    "patio" : "veranda",
    "spacious" : "ferah",
    "terrace" : "teras",
    "strict" : "sıkı",
    "benefit" : "fayda",
    "debt" : "borç",
    "separately" : "ayrı ayrı",
    "awake" : "uyanmak",
    "stand for" : "temsil etmek",
    "approach" : "yaklaşmak",
    "accountancy" : "muhasebe",
    "apprenticeship" : "çıraklık",
    "solution" : "çözüm",
    "recruitment" : "işe alım",
    "stain" : "lekelemek",
    "eternally" : "sonsuza dek",
    "citizen" : "vatandaş",
    "extensive" : "yaygın",
    "receive" : "almak",
    "rehearse" : "prova yapmak",
    "omament" : "süsleme",
    "bury" : "gömmek",
    "setlle" : "yerleşmek",
    "permanently" : "kalıcı olarak",
    "occupant" : "işgalci",
    "decorate" : "dekorasyon",
    "venue" : "mekan",
    "permanent" : "kalıcı",
    "redundant" : "işten çıkarılma",
    "sack (sert işten çıkarılma)" : "kovmak",
    "compensation" : "tazminat",
    "consideration" : "düşünce",
    "demonstrate" : "göstermek",
    "demonstration" : "izah",
    "temptation" : "ayıp",
    "tempt" : "ikna etmeye çalışmak",
    "treat" : "tedavi etmek",
    "convince" : "ikna etmek",
    "starve" : "açlıktan ölmek",
    "refund" : "iade",
    "in charge of" : "sorumlu",
    "instinct" : "içgüdü",
    "improvise" : "doğaçlama",
    "intimidating" : "korkutucu",
    "dreaded" : "korkulan",
    "in exchange for" : "karşılığında",
    "interchangeable" : "değiştirilebilir",
    "untangle" : "çözmek",
    "tangle" : "iç içe geçmek",
    "acknowledge" : "kabullenmek",
    "pretend" : "davranmak",
    "existence" : "varoluş",
    "publicity" : "tanıtım",
    "exception" : "istisna",
    "eventually" : "sonunda",
    "compensation" : "tazminat",
    "complaint" : "şikayet",
    "influential" : "etkili",
    "particular" : "özel",
    "landmark" : "dönüm noktası",
    "admire" : "beğenmek",
    "wealthy" : "zengin",
    "passionately" : "tutkuyla",
    "magnificent" : "muhteşem",
    "go bankrupt" : "iflas etmek",
    "particularly" : "özellikle",
    "accompany" : "eşlik etmek",
    "inhabitant" : "sakin",
    "deliberately" : "kasten",
    "ruin" : "harabe",
    "foolproof" : "kusursuz",
    "geek (öğrenci)" : "inek",
    "good-natured rivalry" : "dostça rekabet",
    "gut feeling" : "içigüdü",
    "job seeker" : "iş arayan",
    "posession" : "mülk",
    "star" : "yıldız",
    "guilty pleasure" : "suçluluk duyulan zevk",
    "defensive" : "savunmacı",
    "coincidence" : "raslantı",
    "weird" : "garip",
    "graphology" : "yazı bilimi",
    "palmistry" : "el falı",
    "recruitment" : "işe alım",
    "candidate" : "aday",
    "cover letter" : "ön söz",
    "enemy" : "düşman",
    "probability" : "olasılık",
    "exaggeration" : "abartı",
    "decent" : "düzgün",
    "baffle" : "şaşırtmak",
    "remote (far away)" : "uzak",
    "roast (argo)" : "yermek",
    "relieve" : "içi rahatlamak",
    "extraordinary" : "olağan dışı",
    "trace" : "iz",
    "bizarre" : "tuhaf",
    "odd" : "garip",
    "spooky" : "ürkütücü",
    "choke" : "boğulmak",
    "come round" : "uğramak",
    "diarrhoea" : "ishal",
    "sprain" : "burkmak",
    "vomit" : "kusmak",
    "checked (desen)"  : "kareli",
    "cotton vest" : "pamuklu yelek",
    "denim waistcoat" : "kot yelek",
    "lace top" : "dantel",
    "linen suit" : "keten takım elbise",
    "long-sleeved" : "uzun kollu",
    "loose (geniş giysi)" : "bol",
    "patterned" : "desenli",
    "plain" : "ova",
    "scruffy" : "kırışık",
    "velvet bow tie" : "kadife papyon",
    "wool" : "yün",
    "rub" : "ovmak",
    "indigestion" : "hazımsızlık",
    "surgeon" : "cerrah",
    "diagnosis" : "teşhis",
    "discriminate" : "ayırt etmek",
    "remedy" : "çare",
    "entrepreneur" : "girişimci",
    "gap" : "aralık",
    "exploit" : "faydalanmak",
    "shrink" : "psikiyatrist",
    "reversal" : "tersine çevirme",
    "intensive" : "yoğun",
    "convince" : "ikna etmek",
    "latter" : "ikincisi",
    "reveal" : "ortaya çıkarmak",
    "unreliable" : "güvenilmez",
    "glamorous" : "göz alıcı",
    "impulsive" : "düşüncesiz",
    "lively" : "canlı",
    "represent" : "temsil etmek",
    "hit it off" : "iyi geçinmek",
    "age gap" : "yaş farkı",
    "take sides" : "taraf tutmak",
    "couldn't care less" : "umrumda değil",
    "look up to" : "hürmet etmek",
    "aisle" : "koridor",
    "airport terminal": "havaalanı terminali",
    "baggage drop": "bagaj bırakma noktası",
    "baggage reclaim": "bagaj alma",
    "board": "pano", 
    "boarding pass": "biniş kartı",
    "business": "işletme",
    "cabin crew": "kabin ekibi",
    "check": "kontrol etmek",
    "check in": "giriş yapmak",
    "check-in desk": "giriş masası",
    "closed": "kapalı",
    "collect": "toplamak",
    "connecting flight": "aktarma uçuşu",
    "customs": "gümrük",
    "delayed": "gecikmiş",
    "departures board": "kalkışlar panosu",
    "direct flight": "direkt uçuş",
    "drop off": "bırakmak",
    "first class": "birinci sınıf",
    "flight time": "uçuş saati",
    "fill in": "doldurmak",
    "gate": "kapı",
    "get off": "inmek",
    "get on": "binmek",
    "hand luggage": "el valizi",
    "illegal goods": "yasa dışı mallar",
    "jet lag": "jet lag",
    "journey": "yolculuk",
    "land": "iniş yapmak",
    "liquid": "sıvı",
    "long-haul flight": "uzun mesafe uçuşu",
    "lounge": "salon",
    "luggage": "bagaj",
    "on time": "zamanında",
    "pick up": "almak",
    "row": "sıra",
    "runway": "pist",
    "scan": "taramak",
    "seat belt": "emniyet kemeri",
    "security": "güvenlik",
    "sharp object": "kesici nesne",
    "take off (uçağın kalkması)": "havalanmak",
    "trip": "seyehat",
    "turbulence": "türbülans",
    "actually": "aslında",
    "apparently": "görünüşe göre",
    "at the end": "sonunda",
    "at the moment": "şu anda",
    "basically": "basitçe",
    "certainly": "kesinlikle",
    "especially": "özellikle",
    "even": "hatta",
    "eventually": "sonunda",
    "ever": "hiç",
    "gradually": "yavaş yavaş",
    "hard": "zor",
    "hardly ever": "neredeyse hiç",
    "hardly" : "zorla",
    "ideally": "ideal olarak",
    "in fact": "aslında",
    "in the end": "sonunda",
    "late": "geç",
    "lately": "son zamanlarda",
    "near": "yakın",
    "nearly": "neredeyse",
    "obviously": "açıkça",
    "specially": "özel olarak",
    "still": "hala",
    "yet": "henüz",
    "below zero": "sıfırın altında",
    "blizzard": "kar fırtınası",
    "boiling": "kaynar",
    "breeze": "esinti",
    "bright": "parlak",
    "changeable": "değişken",
    "chilly": "serin",
    "clear": "temiz",
    "cool": "serin",
    "damp": "nemli",
    "drizzle": "çiselemek",
    "drought": "kuraklık",
    "flood": "sel",
    "fog": "sis",
    "freezing": "dondurucu",
    "hail": "dolu",
    "heatwave": "sıcak hava dalgası",
    "heavy": "yoğun",
    "humid": "nemli",
    "hurricane": "kasırga",
    "icy": "buzlu",
    "lightning": "şimşek",
    "mild": "ılıman",
    "mist": "hafif sis",
    "monsoon": "mevsim rüzgarı",
    "pour": "şakır şakır yağmak",
    "settled": "istikrarlı",
    "shower": "sağanak",
    "smoke": "duman",
    "strong": "kuvvetli",
    "sunny": "güneşli",
    "thick": "yoğun",
    "thunder": "gök gürültüsü",
    "warm": "ılık",
    "take advantage of": "yararlanmak",
    "take after (aile üyesi)": "çekmek",
    "take care of": "ilgilenmek",
    "take into account": "dikkate almak",
    "take no notice of": "aldırmamak",
    "take off": "kalkmak",
    "take (sth) off": "çıkarmak",
    "take (sb) out": "dışarı çıkarmak",
    "take (sth) out": "çıkarmak",
    "take part in": "katılmak",
    "take pity on": "acımak",
    "take place": "gerçekleşmek",
    "take risks": "risk almak",
    "take (your) time": "zaman ayırmak",
    "take to": "almak",
    "take up": "başlamak",
    "despite" : "rağmen",
    "keen" : "hevesli",
    "insist" : "ısrar etmek",
    "spite" : "inat",
        "astronomer": "astronom",
    "astronomical": "astronomik",
    "astronomy": "astronomi",
    "biological": "biyolojik",
    "biologist": "biyolog",
    "biology": "biyoloji",
    "botanical": "botanik",
    "botanist": "botanikçi",
    "botany": "botanik",
    "chemical": "kimyasal",
    "chemist": "kimyager",
    "chemistry": "kimya",
    "clone": "klon",
    "discovery": "keşif",
    "drugs": "ilaçlar",
    "experiment": "deney",
    "genetic": "genetik",
    "geneticist": "genetikçi",
    "genetics": "genetik",
    "guinea pig": "kobay",
    "laboratory": "laboratuvar",
    "physical": "fiziksel",
    "physicist": "fizikçi",
    "physics": "fizik",
    "research": "araştırma",
    "science": "bilim",
    "scientific": "bilimsel",
    "scientist": "bilim insanı",
    "side effect": "yan etki",
    "test": "test",
    "theory": "teori",
    "zoological": "zoolojik",
    "zoologist": "hayvan bilimci",
    "zoology": "hayvan bilimi",
    "all or nothing": "ya hep ya hiç",
    "backwards and forwards": "ileri geri",
    "bits and pieces": "ufak tefek şeyler",
    "by and large": "genel olarak",
    "cause and effect": "neden ve sonuç",
    "dead or alive": "ölü ya da diri",
    "forgive and forget": "affet ve unut",
    "health and safety": "sağlık ve güvenlik",
    "law and order": "kanun ve düzen",
    "live and learn": "yaşa ve öğren",
    "more or less": "aşağı yukarı",
    "now and again": "ara sıra",
    "now or never": "ya şimdi ya hiç",
    "once or twice": "bir iki kez",
    "peace and quiet": "huzur ve sessizlik",
    "pros and cons": "artılar ve eksiler",
    "rain or shine": "hava ne olursa olsun",
    "right or wrong": "doğru ya da yanlış",
    "safe and sound": "sağ salim",
    "short and sweet": "kısa ve öz",
    "sick and tired": "bıkmış ve yorgun",
    "sooner or later": "er ya da geç",
    "supply and demand": "arz ve talep",
    "thunder and lightning": "gök gürültüsü ve şimşek",
    "touch and go": "belirsiz",
    "wait and see": "bekle ve gör",
    "reflect": "yansıtmak",
    "scatter": "dağıtmak",
    "dissolve (suda)": "çözmek",
    "rotate": "döndürmek",
    "moist": "nemli",
    "vapour": "buhar",
    "gravity": "yer çekimi",
    "teleport": "ışınlamak",
    "plausible": "makul",
    "obstacle": "engel",
    "speculative": "spekülatif",
    "mention": "bahsetmek",
    "applaud": "alkışlamak",
    "attribute to": "atfetmek",
    "prolonged": "uzamış",
    "restore": "tadilat",
    "expand": "genişletmek",
    "contract": "sözleşme",
    "invisible": "görünmez",
    "acquisition": "edinim",
    "boost": "arttırmak",
    "advertising campaign": "reklam kampanyası",
    "advertisments": "reklamlar",
    "brand": "marka",
    "consumer": "tüketici",
    "misleading": "yanıltıcı",
    "publicity": "tanıtım",
    "slogan": "slogan",
    "sue": "dava etmek",
    "any other business": "başka bir iş",
    "become the market leader": "pazar lideri olmak",
    "boom": "patlama",
    "branch": "şube",
    "chain": "zincir",
    "ashamed" : "mahçup",
    "close down": "kapatmak",
    "do a deal": "anlaşma yapmak",
    "do a job": "iş yapmak",
    "do badly": "kötü gitmek",
    "do business": "iş yapmak",
    "do market research": "pazar araştırması yapmak",
    "do well": "iyi gitmek",
    "drop": "düşmek",
    "expand": "genişlemek",
    "export": "ihraç etmek",
    "flop": "başarısızlık",
    "get down to business": "işe koyulmak",
    "go out of business": "işi kapatmak",
    "grow": "büyümek",
    "head office": "merkez ofis",
    "import": "ithal etmek",
    "launch": "başlatmak",
    "make a decision": "karar vermek",
    "make a loss": "zarar etmek",
    "make a profit": "kar etmek",
    "make money": "para kazanmak",
    "make (sb) redundant": "birini işten çıkarmak",
    "mean business": "ciddi olmak",
    "merge": "birleşmek",
    "mind your own business": "kendi işine bak",
    "mix business with pleasure": "eğlenerek çalışmak",
    "none of your business": "seni ilgilendirmez",
    "produce": "üretmek",
    "recession": "durgunluk",
    "set up": "kurmak",
    "take over": "devralmak",
    "unfinished business": "bitmemiş iş",
    "absence": "yokluk",
    "abundance": "bolluk",
    "accommodation": "konaklama",
    "alcoholism": "alkol bağımlılığı",
    "antisocial": "asosyal",
    "autopilot": "otomatik pilot",
    "belief": "inanç",
    "bilingual": "iki dil bilen",
    "brotherhood": "kardeşlik",
    "bulletproof": "kurşun geçirmez",
    "careful": "dikkatli",
    "childhood": "çocukluk",
    "coldness": "soğukluk",
    "connection": "bağlantı",
    "convenience": "kolaylık",
    "death": "ölüm",
    "development": "gelişme",
    "distance": "mesafe",
    "employment": "istihdam",
    "entertainment": "eğlence",
    "excitement": "heyecan",
    "expectation": "beklenti",
    "friendliness": "dostluk",
    "government": "hükümet",
    "heat": "sıcaklık",
    "height": "yükseklik",
    "homeless": "evsiz",
    "hopeless": "umutsuz",
    "hunger": "açlık",
    "ignorance": "cehalet",
    "improvement": "gelişim",
    "intention": "niyet",
    "loneliness": "yalnızlık",
    "loss": "kayıp",
    "megacity": "mega şehir",
    "misunderstood": "yanlış anlaşılmış",
    "modernism": "modernizm",
    "monorail": "tek raylı",
    "multicultural": "çok kültürlü",
    "neighbourhood": "mahalle",
    "overcrowded": "aşırı kalabalık",
    "pollution": "kirlilik",
    "postgraduate": "lisansüstü",
    "racism": "ırkçılık",
    "silence": "sessizlik",
    "strength": "güç",
    "subway": "metro",
    "success": "başarı",
    "thought": "düşünce",
    "ugliness": "çirkinlik",
    "unbreakable": "kırılmaz",
    "underdeveloped": "az gelişmiş",
    "undrinkable": "içilemez",
    "useful": "kullanışlı",
    "vandalism": "vandallık",
    "violence": "şiddet",
    "waterproof": "su geçirmez",
    "weakness": "zayıflık",
    "width": "genişlik",
    "pop-up": "ani",
    "disposable": "tek kullanımlık",
    "manufacture": "üretim",
    "distribute": "dağıtmak",
    "compatible": "uyumlu",
    "impose": "dayatmak",
    "cynical": "alaycı",
    "fundamental": "temel",
    "prioritize": "öncelik vermek",
    "head": "baş",
    "a lack of": "eksiklik",
    "state-of-the-art": "son teknoloji",
    "sparsely": "seyrek",
    "spraw": "yayılmak",
    "abundant": "bol",
    "reputation": "ün",
    "vibrant": "canlı",
    "banish": "sürgün etmek",
    "convenience": "kolaylık",
    "fulfill": "yerine getirmek",
        # Crime and punishment
    "accuse": "suçlamak",
    "acquit": "beraat",
    "arrest": "tutuklamak",
    "blackmail": "şantaj yapmak",
    "bribery": "rüşvet",
    "burglary": "hırsızlık (ev/bina)",
    "catch": "yakalamak",
    "commit": "işlemek (suç)",
    "court": "mahkeme",
    "drug dealing": "uyuşturucu satışı",
    "evidence": "kanıt",
    "fraud": "dolandırıcılık",
    "guilty": "suçlu",
    "hacking": "bilgisayar korsanlığı",
    "hijacking (araç gasp etme)": "kaçırma",
    "innocent": "masum",
    "investigate": "soruşturmak",
    "judge (noun)": "yargıç",
    "judge (verb)" : "yargılamak",
    "jury": "jüri",
    "kidnapping": "adam kaçırma",
    "mugging": "yol kesme",
    "murder": "cinayet",
    "proof": "kanıt",
    "punishment": "ceza",
    "question": "soru",
    "rape": "tecavüz",
    "robbery": "soygun",
    "sentence (mahkeme diliyle)": "hüküm",
    "smuggling": "kaçakçılık",
    "stalking": "takip etme",
    "terrorism": "terörizm",
    "theft": "hırsızlık",
    "vandalism": "vandalizm",
    "verdict (mahkeme)": "karar",
    "witness": "tanık",

    # The media
    "accurate": "kesin",
    "agony aunt": "danışman köşe yazarı",
    "axe (bir işi)": "baltalamak",
    "back": "desteklemek",
    "biased": "taraflı",
    "bid": "teklif vermek",
    "censored": "sansürlenmiş",
    "clash": "çatışmak",
    "commentator": "spor yorumcusu",
    "critic": "eleştirmen",
    "editor": "editör",
    "freelance journalist": "serbest gazeteci",
    "hit": "vurmak",
    "newsreader": "haber sunucusu",
    "objective": "tarafsız",
    "paparazzi (aynısını yaz geç ne olduğunu biliyorsun)": "paparazzi",
    "presenter": "sunucu",
    "quit (iş)": "çıkmak",
    "quiz": "sınav",
    "reporter": "muhabir",
    "sensational": "sansasyonel",
    "split": "ayrılmak",
    "tip": "favori göstermek",
    "vow": "yemin etmek",
    "wed": "evlenmek",

    # More words and phrases
    "vandalize": "tahrip etmek",
    "con": "kandırmak",
    "prey on": "avlamak",
    "hand over": "teslim etmek",
    "wary": "ihtiyatlı",
    "breed": "üremek",
    "defeat": "yenilgi",
    "reality": "gerçeklik",
    "expert": "uzman",
    "have a critical eye on sth": "eleştirel gözle bakmak",
    "wipe sth off": "veri silmek",
    "hint": "ima",
    "purport": "iddia etmek",
    "ensure": "emin olmak",
    "accuracy": "doğruluk",
    "source": "kaynak",
    "uncover": "ortaya çıkarmak",
    "purpose": "amaç",
    "burgle": "hırsızlık yapmak",
    "burglar": "hırsız",
    "break into": "zorla girmek",
    "bribe": "rüşvet",
    "victim": "kurban",
    "permission": "izin",
    "scam": "dolandırıcılık",
    "scammer": "dolandırıcı",
    "make use of": "yararlanmak",
    "trick": "hile",
    "glance": "göz atmak",
    "claim": "iddia",
    "conscious": "bilinçli",
    "identity": "kimlik",
    "celebrity": "ünlü",
       # Verbs often confused
    "advise": "tavsiye etmek",
    "argue": "tartışmak",
    "avoid": "kaçınmak",
    "beat": "yenmek",
    "borrow": "ödünç almak",
    "deny": "inkar etmek",
    "expect": "ummak",
    "hope": "umut",
    "lay": "sermek",
    "lend": "ödünç vermek",
    "lie": "yatmak (yatay pozisyon)",
    "mind": "umursamak",
    "notice": "fark etmek",
    "prevent": "engellemek",
    "raise": "yükseltmek",
    "realize": "farkına varmak",
    "refuse": "reddetmek",
    "remember": "hatırlamak",
    "remind": "hatırlatmak",
    "rise": "yükselmek",
    "rob": "soymak",
    "steal": "çalmak",
    "wait": "beklemek",
    "warn": "uyarmak",
    "win": "kazanmak",
    "wish": "dilemek",

    # The body
    "ankle": "ayak bileği",
    "bite your nails": "tırnaklarını yemek",
    "blow your nose": "burnunu silmek",
    "bottom": "kalça",
    "brain": "beyin",
    "brush your hair": "saçını taramak",
    "brush your teeth": "dişlerini fırçalamak",
    "calf": "baldır",
    "cheek": "yanak",
    "chest (a body part)": "göğüs",
    "chew": "çiğnemek",
    "chin": "çene",
    "comb your hair": "saçını taramak",
    "elbow": "dirsek",
    "eye": "göz",
    "eyebrow": "kaş",
    "eyelash": "kirpik",
    "eyelid": "göz kapağı",
    "fist": "yumruk",
    "fold your arms": "kollarını kavuşturmak",
    "forehead": "alın",
    "frown": "kaşlarını çatmak",
    "heart": "kalp",
    "heel": "topuk",
    "hip": "kalça",
    "hold someone's hand": "elini tutmak",
    "hug": "sarılmak",
    "kidneys": "böbrekler",
    "knee": "diz",
    "kneel": "diz çökmek",
    "lips": "dudaklar",
    "liver": "karaciğer",
    "lungs": "akciğerler",
    "nails": "tırnaklar",
    "neck": "boyun",
    "palm": "avuç içi",
    "raise your eyebrows": "kaşlarını kaldırmak",
    "scratch": "çizik",
    "shake hands": "el sıkışmak",
    "shake your head": "hayır demek için başını sallamak",
    "shrug your shoulders": "omuz silkmek",
    "stare": "gözlerini dikmek",
    "stretch": "germek",
    "stubble": "tıraşsız sakal",
    "suck your thumb": "baş parmağını emmek",
    "thigh (kemik)": "uyluk",
    "touch your toes": "parmak uçlarına dokunmak",
    "waist": "bel",
    "wave": "el sallamak",
    "wink": "göz kırpmak",
    "wrinkles": "kırışıklıklar",
    "wrist": "bilek",
    "yawn": "esnemek",

    # More words and phrases
    "pile": "yığın",
    "housemate": "ev arkadaşı",
    "joint": "ortak",
    "label (verb)": "etiketlemek",
    "label (noun)": "etiket",
    "soften": "yumuşatmak",
    "decisive": "kararlı",
    "non-verbal": "sözsüz",
    "consequence": "sonuç",
    "recruit": "işe almak",
    "convincing": "ikna edici",
    "spot": "fark etmek",
    "striking": "çarpıcı",
    "cut off": "kesmek",
    "criticize": "eleştirmek",
    "contribute": "katkıda bulunmak",
    "deal with": "ile başa çıkmak",
    "convince": "ikna etmek",
    "adjust": "ayarlamak",
    "enormous": "muazzam",
    "establish": "kurmak",
    "intend": "niyet etmek",
    "obvious": "bariz",
    "involve": "dahil etmek",
    "share": "paylaşmak",
    "fault": "hata",
    "abolish": "yasa kaldırmak",
    "intonation": "tonlama",
    "expression": "ifade",
    "analyse": "analiz",
    "challenge": "meydan okuma",
    "alternative": "alternatif",
    "reply": "yanıt",
    "suggest": "önermek",
    "instantly": "anında",
    "case": "dava",
    "significantly": "önemli ölçüde",
    "mime": "pandomim yapmak",
    "break off": "koparmak",
    "unsure": "kararsız",
    "be between jobs": "işsiz olmak",
    "carry on": "devam etmek",
    "benefit": "yarar sağlamak",
    "come up with (fikir / çözüm)": "bulmak",
    "identify": "tanımlamak",
    "suspicious": "şüpheli",
    "prove": "kanıtlamak",
    "effective": "etkili",
    "lie": "yalan",
    "liar": "yalancı",
    "pretend": "rol yapmak",
    "familiar": "tanıdık",
    "tend": "eğilim göstermek",
    "indicate": "göstermek",
    "rely on": "güvenmek",
    "unreliable": "güvenilmez",
    "reliable": "güvenilir",
    "selection": "seçim",
    "fee": "ücret",
    "purpose": "amaç",
    "valid": "geçerli",
    "require": "gerektirmek",
    "expected": "beklenen",
    "unexpected": "beklenmedik",
    "accurately": "doğru şekilde",
    "tendency": "eğilim",
    "reveal": "açığa çıkarmak",
    "limit": "sınır",
        # Feelings (Adjectives)
    "astonished": "şaşkına dönmüş",
    "bewildered": "şaşkın",
    "delighted": "çok mutlu",
    "desperate": "umutsuz",
    "devastated": "mahvolmuş",
    "disappointed": "hayal kırıklığına uğramış",
    "down": "aşağı",
    "down (ruh hali)" : "morali bozuk",
    "fed up": "bıkmış",
    "gobsmacked": "şaşkına dönmüş",
    "grateful": "minnettar",
    "gutted": "perişan",
    "homesick": "vatan hasreti çeken",
    "horrified": "dehşete düşmüş",
    "lonely": "yalnız",
    "miserable": "perişan",
    "offended": "alınmış",
    "overwhelmed": "bunalmış",
    "proud": "gururlu",
    "relieved": "rahatlamış",
    "scared stiff": "korkudan donakalmış",
    "shattered": "bitkin",
    "sick of": "bıkmak",
    "stunned": "şok edici",
    "thrilled": "çok heyecanlı",
    "upset": "üzgün",

    # Expressing feelings with verbs or adjectives
    "amaze": "şaşırtmak",
    "confuse": "kafasını karıştırmak",
    "disappoint": "hayal kırıklığına uğratmak",
    "embarrass": "utandırmak",
    "exhaust": "tüketmek",
    "frustrate": " 	hayal kırıklığına uğratmak",
    "infuriate": "çıldırtmak",
    "inspire": "ilham vermek",
    "terrify": "çok korkutmak",
    "thrill": "heyecanlandırmak",

    # More words and phrases
    "confront": "yüzleştirmek",
    "intruder": "işgalci",
    "curl into": "kıvrılmak",
    "surface": "yüzey",
    "feature": "özellik",
    "ultimate": "nihai",
    "shelter (hayvan)": "barınak",
    "navigate": "yön bulmak",
    "go backpacking": "otostop",
    "civilization": "medeniyet",
    "infected": "enfekte",
    "abandon": "terk etmek",
    "attempt": "teşebbüs",
    "buzzing": "vızıltı",
    "buzz" : "hevesli",
    "rejection": "reddedilme",
    "declare": "açıklamak",
    "memoir": "anı",
    "fragmented": "parçalanmış",
    "gear": "vites",
    "handbrake": "el freni",
    "afloat": "su üstünde",
    "off-piste": "patika dışı",
    "uninhabited": "ıssız",
    "ski pole": "kayak batonu",
    "strand": "mahsur kalmak",
    "appeal": "çekici gelmek",
    "a range of": "bir dizi",
    "though": "gerçi, rağmen",
    "creepy crawlies": "ürkütücü böcekler",
    "indigenous": "yerli",
    "raft": "sal",
    "tension": "gerilim",
    "unfulfilled": "yerine getirilmemiş",
    "regret": "pişman olmak",
    "intriguingly": "ilginç bir şekilde",
        # Weather
    "below zero": "sıfırın altında",
    "blizzard": "kar fırtınası",
    "boiling": "kaynar gibi (çok sıcak)",
    "breeze": "hafif rüzgar",
    "clear (hava)": "açık",
    "cool": "serin",
    "drizzle": "çiselemek",
    "drought": "kuraklık",
    "flood": "sel",
    "fog": "sis",
    "freezing": "dondurucu soğuk",
    "hail": "dolu",
    "heatwave": "sıcak hava dalgası",
    "heavy (rain/weather)": "şiddetli",
    "humid": "nemli",
    "hurricane": "kasırga",
    "icy": "buzlu",
    "lightning": "şimşek",
    "mild": "ılıman",
    "mist": "hafif sis",
    "monsoon": "muson yağmurları",
    "shower": "sağanak",
    "smog": "hava kirliliği",
    "strong (rüzgar)": "kuvvetli",
    "sunny": "güneşli",
    "thick": "yoğun (sis/duman)",
    "thunder": "gök gürültüsü",
    "warm": "ılık",

    # Expressions with 'take'
    "take advantage of": "yararlanmak, fırsatı değerlendirmek",
    "take against": "karşı olmak",
    "take into account": "göz önünde bulundurmak",
    "take off": "kalkış yapmak (uçak); çıkarmak (giysi)",
    "take (sth) off (giysi)": "çıkarmak",
    "take (sth) out": "çıkarmak (çöp vb.)",
    "take part in": "katılmak",
    "take place": "gerçekleşmek",
    "take risks": "risk almak",
    "take (your) time": "acele etmemek",
    "take to": "hoşlanmaya başlamak",
    "take up": "başlamak",

    # More words and phrases
    "impact": "etki",
    "significant": "önemli",
    "predict": "tahmin etmek",
    "erode": "aşındırmak",
    "property": "mülk",
    "desertification": "çölleşme",
    "online dating": "çevrimiçi flört",
    "dye": "boyamak",
    "proportion": "oran",
    "get addicted": "bağımlı olmak",
    "skydiving": "hava dalışı",
    "GoPro": "aksiyon kamerası",
    "paraglide": "yamaç paraşütü",
    "wingsuit flying": "wingsuit uçuşu",
    "summit": "zirve",
    "dramatically": "aniden",
    "reduce": "azaltmak",
    "erupt (yanardağ)": "patlamak",
    "accessible": "erişilebilir",
    "worthwhile": "zahmete değer",
    "die out": "soyu tükenmek",
    "run out": "tükenmek",
    "occurance": "meydana gelme",
    "ultimate": "nihai",
    "opponent": "rakip",
        # Air Travel
    "airport terminal": "havaalanı terminali",
    "baggage drop": "bagaj bırakma",
    "baggage reclaim": "bagaj teslim alanı",
    "board (uçak)": "uçağa binmek",
    "boarding pass": "biniş kartı",
    "cabin crew": "kabin ekibi",
    "check": "kontrol etmek",
    "check in": "check-in yapmak",
    "closed": "kapalı",
    "connecting flight": "aktarmalı uçuş",
    "customs": "gümrük",
    "delayed": "gecikmiş",
    "departures board": "kalkışlar panosu",
    "direct flight": "direkt uçuş",
    "drop off": "bırakmak",
    "first class": "birinci sınıf",
    "flight time": "uçuş saati",
    "hand luggage": "el bagajı",
    "illegal goods": "yasa dışı mallar",
    "jet lag": "uçuş yorgunluğu",
    "journey": "yolculuk",
    "land": "iniş yapmak",
    "liquid": "sıvı",
    "long-haul flight": "uzun mesafe uçuş",
    "luggage": "bagaj",
    "on time": "zamanında",
    "runway": "pist",
    "scan": "taramak",
    "seat belt": "emniyet kemeri",
    "security": "güvenlik",
    "sharp object": "kesici nesne",
    "take off": "kalkış yapmak",
    "travel": "seyahat",
    "trip": "gezi",
    "trolley": "el arabası",
    "turbulence": "türbülans",

    # Adverbs and adverbial phrases
    "actually": "aslında",
    "apparently": "görünüşe göre",
    "at the end": "sonunda",
    "at the moment": "şu anda",
    "certainly": "kesinlikle",
    "especially": "özellikle",
    "even": "hatta",
    "eventually": "sonunda",
    "gradually": "yavaş yavaş",
    "hardly": "neredeyse hiç",
    "ideally": "ideal olarak",
    "in fact": "aslında",
    "in the end": "sonunda",
    "late": "geç",
    "near": "yakın",
    "nearly": "neredeyse",
    "obviously": "açıkça",
    "specially": "özel olarak",
    "still": "hala",
    "yet": "henüz",

    # More words and phrases
    "locate": "yerini bulmak",
    "proceed to": "başlamak",
    "negotitate" : "görüşmek",
    "disembark": "tahliye",
    "sift": "elemek",
    "travel light": "az eşya ile seyahatb",
    "grab": "kapmak",
    "rear": "arka",
    "restriction": "kısıtlama",
    "willing": "istekli",
    "altitude": "irtifa",
    "evacuation": "tahliye",
    "aircraft": "uçak",
    "suffocating": "boğucu",
    "whisper": "fısıldamak",
    "absolutely": "kesinlikle",
    "manual": "el kitabı",
    "hesitate": "tereddüt etmek",
    "wipe": "silmek",
    "proper": "uygun",
    "distress": "sıkıntı",
    "accumulation": "birikim",
    "steady": "sabit",
    "inability": "yetersizlik",
    "companion": "yoldaş",
    "frustrated": "hayal kırıklığına uğramış",
    "revenge": "intikam",
    "dismiss": "göz ardı etmek",
    "worn out (bir nesne)": "yıpranmış",
    "worn out (insan)" : "bitkin",
    "insult": "hakaret etmek",
        # Illnesses and injuries
    "allergic reaction": "alerjik reaksiyon",
    "be sick": "hasta olmak",
    "bleed": "kanamak",
    "blister": "su toplaması",
    "blood pressure": "tansiyon",
    "burn": "yanmak",
    "choke": "boğulmak",
    "cold (hastalık)": "soğuk algınlığı",
    "come round": "kendine gelmek",
    "cough": "öksürük",
    "cut": "kesmek",
    "diarrhoea": "ishal",
    "dizzy": "başı dönen",
    "earache": "kulak ağrısı",
    "faint": "bayılmak",
    "feel sick": "midesi bulanmak",
    "flu": "grip",
    "food poisoning": "gıda zehirlenmesi",
    "get over": "üstesinden gelmek",
    "headache": "baş ağrısı",
    "hurt": "acımak",
    "lie down": "uzanmak",
    "pass out": "bayılmak",
    "rash": "döküntü",
    "sore throat": "boğaz ağrısı",
    "sprain": "burkmak",
    "stomach ache": "karın ağrısı",
    "sunburn": "güneş yanığı",
    "swell": "şişmek",
    "temperature": "sıcaklık",
    "throw up": "kusmak",
    "toothache": "diş ağrısı",
    "unconscious": "bilinçsiz",
    "vomit": "kusmak",

    # Clothes and fashion
    "casual": "gündelik, rahat",
    "classic": "klasik",
    "cotton vest": "pamuklu atlet",
    "dress up": "şık giyinmek",
    "fit (beden)": "uymak",
    "fur collar": "kürk yakalı",
    "get changed": "üstünü değiştirmek",
    "get dressed": "giyinmek",
    "get undressed": "soyunmak",
    "go with": "uyum sağlamak",
    "hang up (giysi)": "asmak",
    "hooded": "kapüşonlu",
    "lace top": "dantel üst",
    "leather sandals": "deri sandalet",
    "linen suit": "keten takım",
    "long-sleeved": "uzun kollu",
    "lycra swimsuit": "likra mayo",
    "match (biriyle)": "eşleşmek",
    "old-fashioned": "modası geçmiş",
    "patterned": "desenli",
    "plain": "sade",
    "silk scarf": "ipek eşarp",
    "sleeveless": "kolsuz",
    "smart": "şık",
    "spotted": "benekli",
    "striped": "çizgili",
    "suede boots": "süet çizme",
    "suit": "yakışmak",
    "velvet bow tie": "kadife papyon",
    "V-neck": "v yaka",
    "wool cardigan": "yün kazak",

    # More words and phrases
    "first aid": "ilk yardım",
    "injection": "enjeksiyon",
    "tip": "bahşiş",
    "rub": "ovmak",
    "indigestion": "hazımsızlık",
    "surgeon": "cerrah",
    "cyberchondriac": "siberkondriyak",
    "diagnosis": "teşhis",
    "send smb off": "birini göndermek",
    "swap": "takas",
    "discriminate": "ayırt etmek",
    "remedy": "çare",
    "miracle": "mucize",
    "entrepreneur": "girişimci",
    "exploit": "sömürmek",
    "shrink (verb)": "küçülmek",
    "reversal": "tersine dönme",
    "intensive": "yoğun",
    "convince": "ikna etmek",
    "reveal": "ortaya çıkarmak",
    "unreliable": "güvenilmez",
    "remove": "kaldırmak",
    "cure": "tedavi",
    "glamorous": "göz alıcı",
    "impulsive": "dürtüsel",
    "lively": "canlı",
    "represent": "temsil etmek",
    "point of view": "bakış açısı",
    "offend" : "kırmak",
    "take sides": "taraf tutmak",
    "look up to": "hayran olmak",
    "good-natured rivalry": "iyi niyetli rekabet",
    "gut feeling": "içgüdü",
    "job-seeker": "iş arayan",
    "light-hearted response": "rahat cevap",
    "the point of": "asıl mesele",
    "work-life balance": "iş hayat dengesi",
    "absent-minded": "unutkan",
    "bad-tempered": "huysuz",
    "big-headed": "kibirli, kendini beğenmiş",
    "easy-going": "rahat",
    "good-tempered": "iyi huylu",
    "laid-back": "gamsız",
    "narrow-minded": "dar görüşlü",
    "open-minded": "açık fikirli",
    "self-centred": "bencil",
    "strong-willed": "irade sahibi",
    "tight-fisted": "cimri",
    "two-faced": "iki yüzlü",
    "well-balanced": "dengeli",
    "well-behaved": "terbiyeli",
    "defensive": "savunmacı",
    "coincidence": "tesadüf",
    "weird": "tuhaf",
    "graphology": "yazı bilimi",
    "palmistry": "el falı",
    "recruitment": "işe alım",
    "candidate": "aday",
    "enemy": "düşman",
    "probability": "olasılık",
    "exaggeration": "abartı",
    "baffle": "şaşırtmak",
    "relieve": "rahatlatmak",
    "speculation": "spekülasyon",
    "invasion": "istila",
    "bizarre": "acayip",
    "odd": "garip",
    "spooky": "ürkütücü",
    
} 
seed = random.randint(2,1000)
random.seed(seed)

def word_game():
    print("Welcome to the Word Guessing Game!")
    print("Type 'quit' to exit the game or 'b' to reveal the answer.")
    global x
    global y
    global z
    
    while True:
        # Rastgele bir kelime seç
        
        english_word, turkish_translation = random.choice(list(words.items()))
        print(f"\nWhat is the meaning of        '{english_word}'      in Turkish?")
        y += 1
        attempts_left = 3  # Her soru için 3 deneme hakkı
        
        while attempts_left > 0:
            guess = input(f"Your guess (Attempts left: {attempts_left}): ").strip().lower()
            
            
            if guess == "quit":
                print("Thanks for playing! Goodbye!")
                z = (x * 100) / y
                print("\nDoğru / Soru "f"\n  {x} / {y}" + f"\t%{int(z)}" )
                return
            
            if guess == "b":
                print(f"The correct answer is: '{turkish_translation}'")
                break
            
            if guess == turkish_translation.lower():
                print("🎉 Correct! You guessed it right.")
                x += 1
                break
            else:
                attempts_left -= 1
                print("❌ Incorrect guess. Try again!")

        if attempts_left == 0:
            print(f"😞 Out of attempts! The correct answer was: '{turkish_translation}'")

# Oyunu başlat
word_game()

